---
- name: install net-misc/ntp
  portage: package=net-misc/ntp
  tags: [install, packages]

- name: configure ntpd
  template: >
    src=ntp.conf.j2
    dest=/etc/ntp.conf
    owner=root group=root mode=0644
  notify: restart ntpd
  tags: config

- name: enable and start ntpd
  service: name=ntpd enabled=yes state=started
  tags: services
